### ISSUE TITLE
[Feature] XMP Support

### ISSUE THREAD

**Issue by leonardocustodio** [justkawal/metadata#1]
Hello,

I've just found your library and it looks great. Still I think there is something missing, I did not find any plugin for flutter that supports to read XMP from files.

Here is the output that I get from a file that has XMP on it:

`{image: {ImageDescription: cdefrefewfq rewrwqrewqrewq rewqr wqerqwr, ExifOffset: 162, XPComment: [97, 0, 98, 0, 99, 0, 100, 0, 101, 0, 102, 0, 103, 0, 104, 0, 32, 0, 114, 0, 113, 0, 119, 0, 32, 0, 114, 0, 101, 0, 119, 0, 113, 0, 32, 0, 114, 0, 113, 0, 119, 0, 101, 0, 32, 0, 114, 0, 101, 0, 119, 0, 113, 0, 32, 0, 114, 0, 113, 0, 119, 0, 101, 0, 32, 0, 114, 0, 113, 0, 119, 0]}, thumbnail: {}, exif: {UserComment: [85, 78, 73, 67, 79, 68, 69, 0, 97, 0, 98, 0, 99, 0, 100, 0, 101, 0, 102, 0, 103, 0, 104, 0, 32, 0, 114, 0, 113, 0, 119, 0, 32, 0, 114, 0, 101, 0, 119, 0, 113, 0, 32, 0, 114, 0, 113, 0, 119, 0, 101, 0, 32, 0, 114, 0, 101, 0, 119, 0, 113, 0, 32, 0, 114, 0, 113, 0, 119, 0, 101, 0, 32, 0, 114, 0, 113, 0, 119, 0]}, gps: {}, interoperability: {}, makernote: {}}`

So the plugin can only see the description and XPComment as well as UserComment but here are the information that this photo also has:

![](https://i.imgur.com/nMjkd7C.gif)

Do you think it would be possible to include the XMP information?

Best regards,

**Comment by justkawal** [comment]
@leonardocustodio I will look into it and will try togive this functionality as soon as I understand it.

**Comment by leonardocustodio** [comment]
This protocol is used by a lot of adobe products and there are many photo editing apps that also uses it for saving information. Like keywords, depth map, filters and a lot of things. Although there are a lot of libraries for reading and saving information on Android. There are no plugins for flutter yet.
For compatibility with iOS and Android you would probably need to do some low-level code with bytes reading since we are not able to use the java libraries on iOS. Or use another library for iOS as well, I know there is a Obj-C wrapper for the official adobe library here: https://github.com/IHEARTCOOKIES/XMPFramework

It is a hard work. But as I said although there are a lot of plugins that can read EXIF, we still have none that can work with XMP. It would be really awesome to see that and finally be possible to integrate with other native apps.

**Comment by justkawal** [comment]
@leonardocustodio 
Now XMP data can be read easily in the updated version.
````metadata: ^1.0.1````

**Comment by leonardocustodio** [comment]
I saw your PR code with just a few lines of change and I was like: "ohhh how I did not find this xmp plugin? Now I'm embarrassed..." Than I saw you made the plugin hahaha. Congratulations man, you are awesome. I'm going to test it today later on.
Thank you for your first issue closed and your awesome new and only plugin that can do that in flutter ;)

**Comment by leonardocustodio** [comment]
Hmm @justkawal there is an error with the plugin,

The same picture above, it returned me this:

`{raw: {dc:description: cdefrefewfq rewrwqrewqrewq rewqr wqerqwr, dc:subject: teste3}, description: cdefrefewfq rewrwqrewqrewq rewqr wqerqwr, subject: teste3}`

The description is right, but at the subject. It's returning me only "teste3"
But there is an array in the picture with the items: ["teste", "teste2", "teste3"] just like the gif above.
For some reason it returns only the last item as plain text.


I also tested another picture that I've just saved:

` {raw: {dc:subject: Spirit}, subject: Spirit}`

And here is what is saved on the subject field:
![](https://i.imgur.com/KzGeEbI.png)

By the way, for testing purposes I recommend using the app for Android: "ExifTool" and for saving information, you can use Adobe Lightroom Classic

Best regards,

**Comment by justkawal** [comment]
@leonardocustodio 
Will surely look at that Android App.
HaHa, Can't look into Adobe Lightroom Classic, My laptop will blast off, (old MacBook Air). haha

I have found out what was causing that.

I will fix this as soon as possible.
Will you please provide me a sample image ?

~Thanks
~ Long Live Open Source.

**Comment by leonardocustodio** [comment]
Sure, give me a couple hours to get home and I will send to you a sample photo with as much metadata as possible xP

**Comment by leonardocustodio** [comment]
Here you go, the link to a sample photo:
https://filebin.net/0w4ijvjpew95cv59/sample_pic.zip?t=7suhhjgi

I filled every metadata info from every protocol on Lightroom, also on Windows. I don't think it is necessary to read all of them haha. I just did so you can have a full sample photo.

Regards,

**Comment by justkawal** [comment]
@leonardocustodio Thanks for the sample image,
I have started working on the fix.

~Thanks

**Comment by leonardocustodio** [comment]
Sure man, thank you for your time on take up on this challenge ;)

**Comment by justkawal** [comment]
@leonardocustodio 
First of Thanks **Leonardo** for that sample image. Without that I would have not gone deeper into XMP Tags.

Deeper XMP data is now available in newer version of metadata : https://github.com/justkawal/metadata 
or xmp : https://github.com/justkawal/xmp
