### ISSUE TITLE
Issue tracker link in pub.dev is broken

### ISSUE THREAD

**Issue by Mabsten** [justkawal/metadata#4]
The link to "View/report issues" in https://pub.dev/packages/metadata is broken pointing to https://github.com/justkawal/metadata.git/issues (note:  **.git**) instead of https://github.com/justkawal/metadata/issues

**Comment by SputNikPlop** [comment]
@justkawal This seems to be fixes on pub.dev

**Comment by justkawal** [comment]
Thanks.
