### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by abulka** [justkawal/metadata#6]
Please upgrade to support null safety. Cannot use at present in Flutter 3

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:metadata

For solutions, see https://dart.dev/go/unsound-null-safety
```

**Comment by SputNikPlop** [comment]
@justkawal I would be happy to monetarily contribute if I could get this package update or do both and maybe submit a PR. Let me know 😺

**Comment by justkawal** [comment]
@abulka 
`metadata: ^2.0.0` is now available with null-safety migrated. https://pub.dev/packages/metadata

**Comment by justkawal** [comment]
> @justkawal I would be happy to monetarily contribute if I could get this package update or do both and maybe submit a PR. Let me know 😺

Much Appreciated  ❤️!!

**Comment by justkawal** [comment]
@SputNikPlop @abulka Please feel free to close, If it resolves the issue.

**Comment by justkawal** [comment]
@SputNikPlop ?? 👀

**Comment by abulka** [comment]
Thank you for doing this - much appreciated.

**Comment by SputNikPlop** [comment]
> @SputNikPlop ?? 👀

I just got back, but yes this is fine. What is the best way to tip you?

**Comment by justkawal** [comment]
Feel free to send 1 bitcoin over paypal... Haha 😂🤝 Will help to pay-off student-loan... Hahaha

> > @SputNikPlop ?? 👀
> 
> I just got back, but yes this is fine. What is the best way to tip you?
